# Generated by Django 2.2.7 on 2019-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books", "0004_auto_20191117_0924")]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("speical_status", "Can read all books")]},
        ),
        migrations.AddIndex(
            model_name="book", index=models.Index(fields=["id"], name="id_index")
        ),
    ]
